name: Node.js Package

on:
  release:
    types: [published]

permissions:
  contents: write # To push updated files back to master
  packages: write # For GitHub packages (optional)
  id-token: write # Required for OIDC trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Publish NPM Package
        uses: phucbm/publish-npm-action@v1 # Docs https://github.com/phucbm/publish-npm-action
        with:
          node-version: '20'
          install-command: 'npm ci'
          test-command: 'npm test'
          build-command: 'npm run build'
          target-branch: 'master'
          skip-tests: 'false'
